// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FullName struct {
	Name       string `json:"name"`
	SecondName string `json:"second_name"`
	LastName   string `json:"last_name"`
}

type Mutation struct {
}

type NewUserInput struct {
	Name         string `json:"name"`
	SecondName   string `json:"second_name"`
	LastName     string `json:"last_name"`
	PassportData string `json:"passport_data"`
	BirthDate    string `json:"birth_date"`
	Email        string `json:"email"`
}

type Query struct {
}

type User struct {
	ID           string    `json:"id"`
	Fullname     *FullName `json:"fullname"`
	Email        string    `json:"email"`
	PassportData string    `json:"passport_data"`
	BirthDate    string    `json:"birth_date"`
}
